server:
  port: 8087
  servlet:
    context-path: /ai-feedback

spring:
  application:
    name: ai-feedback-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_feedback_service
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update   # Ho?c 'none' n?u b?n dùng Flyway/Liquibase
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
