server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: ai-orchestration-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/ai-orchestration/**
          filters:
            - StripPrefix=2

        - id: content-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/content/**
          filters:
            - StripPrefix=2

        - id: class-management-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/class-management-service/**
          filters:
            - StripPrefix=2
#        - id: submission-service
#          uri: http://localhost:8086
#          predicates:
#            - Path=${app.api-prefix}/submission/**
#          filters:
#            - StripPrefix=2
        - id: submission-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/submission/**
          filters:
            - StripPrefix=2

#        - id: ai-feedback-service
#          uri: http://localhost:8087
#          predicates:
#            - Path=${app.api-prefix}/ai-feedback/**
#          filters:
#            - StripPrefix=2
eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: ${HOST_IP_ADDRESS}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka