spring:
  datasource:
    url: jdbc:postgresql://defty-toeic-postgre-fullstack6742-63fe.i.aivencloud.com:23852/question_bank_dev?sslmode=require
    username: avnadmin
    password: AVNS_yhKtgnD9fD_-xlObIjI
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: false
        cache:
          use_second_level_cache: false
          use_query_cache: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000

app:
  api-prefix: /api/v1
  gateway-url: http://localhost:8888
  test-evaluation-service-url: http://localhost:8087
  kafka-topic-test-set-completed: test_set.completed
  kafka-topic-test-set-upload: test_set.upload
#
#openapi:
#  service:
#    server: http://localhost:8888/api/v1/question-bank-service
#
defty:
#  security:
#    enabled: true
#    publicEndpoints: "/**/accessible/**"
#    jwt:
#      expiration: 3600
#      expirationRefreshToken: 86400
#      secretKey: 5d52QxETMTxUyZ2VjgrTMLymN7fLp/++mWpSdfzPrdrPTussUSzOtsotKyl8wEoo
#    cache:
#      maxSize: 1000
#      ttlMinutes: 15
#    redis:
#      host: localhost
#      port: 6379
#      password:
#
#  server-host-info:
#    enabled: ${SERVER_HOST_INFO_ENABLED:true}
#    hostname: ${SERVER_HOSTNAME:103.221.222.128}
#    port-nginx-media: ${SERVER_PORT_NGINX_FILE:81}

  file:
    enabled: true
    cloudinary:
      cloud-name: dc9nyxru6
      api-key: 431649663815195
      api-secret: l0OPyaBmY9BtQ9j_lrVWrWwHAQ4
#
#  server-file:
#    enabled: ${QUESTION_BANK_SERVICE_SERVER_FILE_ENABLED:true}
#    root-dir: /app/shared
#    limits:
#      image-max-size: ${SERVER_FILE_IMAGE_MAX_SIZE:5242880}
#      audio-max-size: ${SERVER_FILE_AUDIO_MAX_SIZE:10485760}
#      video-max-size: ${SERVER_FILE_VIDEO_MAX_SIZE:52428800}
#      document-max-size: ${SERVER_FILE_DOCUMENT_MAX_SIZE:10485760}
#      default-max-size: ${SERVER_FILE_DEFAULT_MAX_SIZE:20971520}
#
#  multipart:
#    enabled: ${MULTIPART_CONFIG_SIZE_ENABLED:true}
#    max-file-size-mb: ${MULTIPART_MAX_FILE_SIZE_MB:150}
#    max-request-size-mb: ${MULTIPART_MAX_REQUEST_SIZE_MB:150}
#
#  kafka:
#    enabled: true
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: question-bank-service
#      auto-offset-reset: earliest

file:
  upload:
    path: D:/exam-files
    max-size: 30MB