server:
  port: 8086

api:
  prefix: /api/v1

spring:
  application:
    name: submission-service

  datasource:
    url: jdbc:postgresql://ep-cold-waterfall-a1ofxb6e-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_cGsM9EZjo0Of&sslmode=require&channelBinding=require

#  datasource:
#    url: jdbc:postgresql://localhost:5432/defty_db
#    username: defty_user
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Đảm bảo sử dụng đúng Dialect cho MySQL 8
        format_sql: true  # Hiển thị SQL đã định dạng đẹp (kèm theo tham số)
        show_sql: false  # In câu lệnh SQL ra console
        use_sql_comments: true  # Thêm các chú thích SQL (nếu cần thiết)
        jdbc:
          batch_size: 50
        order_inserts: true  # Tối ưu hóa chèn hàng loạt
        order_updates: true  # Tối ưu hóa cập nhật hàng loạt
        generate_statistics: false  # Bật thống kê Hibernate

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379
      # password: # Nếu Redis có mật khẩu, hãy bỏ comment và điền vào đây


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: submission-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


PLANTUML_SERVER_URL: http://localhost:8091/svg

eureka:
  client:
    fetch-registry: true
  #  instance:
  #    prefer-ip-address: true
  #    ip-address: ${HOST_IP_ADDRESS}
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      defaultZone: http://localhost:8761/eureka
